'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PowerTray.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property PowerTray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property PowerTrayBlue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayBlue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property PowerTrayGray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayGray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property PowerTrayGreen() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayGreen", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property PowerTrayRed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayRed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;#
        '''.SYNOPSIS
        '''  Info on IPv4 settings
        '''
        '''.DESCRIPTION
        '''  Get IPv4 WellKnow addresses of the system
        '''
        '''.NOTES
        '''  Version:        1.0
        '''  Author:         Ermanno Goletto
        '''  Creation Date:  2019-05-22
        '''#&gt;
        '''
        '''$IPv4Adresses=Get-NetIPAddress -AddressFamily IPv4 | Where-Object PrefixOrigin -ne &apos;WellKnow&apos;
        '''$IPv4Adresses | Format-Table @{Label=&apos;C1&apos;; Expression={$_.InterfaceAlias}}, `
        '''	@{Label=&apos;C2&apos;; Expression={&apos;[&apos;+ $_.PrefixOrigin+&apos;]&apos;}; Alignment=&apos;Left&apos;}, `
        '''	@{Label=&apos;C3&apos;; Expression={&apos;: &apos; + $_.IPAddress+&apos;/&apos;+$_.Pre [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSQuery_IPv4Info() As String
            Get
                Return ResourceManager.GetString("PSQuery_IPv4Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;#
        '''.SYNOPSIS
        '''  Info on last boot up time
        '''
        '''.DESCRIPTION
        '''  Get the date and time the operating system was last restarted
        '''
        '''.NOTES
        '''  Version:        1.0
        '''  Author:         Ermanno Goletto
        '''  Creation Date:  2019-05-23
        '''#&gt;
        '''
        '''
        '''Get-WmiObject -Class Win32_OperatingSystem | Select-Object  @{label=&apos;LastBootUpTime&apos;;expression={$_.ConvertToDateTime($_.LastBootUpTime)}} | Format-Table -HideTableHeaders
        '''
        '''#Get-CimInstance -ClassName win32_operatingsystem | Select-Object LastBootUpTime | Format-Table -HideTable [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSQuery_LastBootUpTime() As String
            Get
                Return ResourceManager.GetString("PSQuery_LastBootUpTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;#
        '''.SYNOPSIS
        '''  Info on last boot up time
        '''
        '''.DESCRIPTION
        '''  Get the date and time the operating system was last restarted
        '''
        '''.NOTES
        '''  Version:        1.0
        '''  Author:         Ermanno Goletto
        '''  Creation Date:  2019-05-23
        '''#&gt;
        '''
        '''$LastBootUpTime=Get-WmiObject -Class Win32_OperatingSystem | Select-Object  @{label=&apos;LastBootUpTime&apos;;expression={$_.ConvertToDateTime($_.LastBootUpTime)}}
        '''$UpTime=New-TimeSpan -Start $LastBootUpTime -End (Get-Date)
        '''$UpTime | Select-Object Days, Hours, Minutes @{Label=&apos;Uptime&apos;; Exp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSQuery_UpTime() As String
            Get
                Return ResourceManager.GetString("PSQuery_UpTime", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
