'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PowerTray.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1040\deflangfe1040\themelang1040\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        '''{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\flomajor\f31500\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New  [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property MIT_License() As String
            Get
                Return ResourceManager.GetString("MIT_License", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property PowerTray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property PowerTrayBlue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayBlue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property PowerTrayGray() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayGray", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property PowerTrayGreen() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayGreen", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        '''</summary>
        Friend ReadOnly Property PowerTrayRed() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PowerTrayRed", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;#
        '''.SYNOPSIS
        '''  Info on IPv4 settings
        '''
        '''.DESCRIPTION
        '''  Get IPv4 WellKnow addresses of the system
        '''
        '''.NOTES
        '''  Version:        1.0
        '''  Author:         Ermanno Goletto
        '''  Creation Date:  2019-05-22
        '''#&gt;
        '''
        '''$IPv4Adresses=Get-NetIPAddress -AddressFamily IPv4 | Where-Object PrefixOrigin -ne &apos;WellKnow&apos;
        '''$IPv4Adresses | Format-Table @{Label=&apos;C1&apos;; Expression={$_.InterfaceAlias}}, `
        '''	@{Label=&apos;C2&apos;; Expression={&apos;[&apos;+ $_.PrefixOrigin+&apos;]&apos;}; Alignment=&apos;Left&apos;}, `
        '''	@{Label=&apos;C3&apos;; Expression={&apos;: &apos; + $_.IPAddress + &apos;/&apos; + $_ [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSQuery_IPv4Info() As String
            Get
                Return ResourceManager.GetString("PSQuery_IPv4Info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;#
        '''.SYNOPSIS
        '''  Info on last boot up time
        '''
        '''.DESCRIPTION
        '''  Get the date and time the operating system was last restarted
        '''
        '''.NOTES
        '''  Version:        1.0
        '''  Author:         Ermanno Goletto
        '''  Creation Date:  2019-05-23
        '''#&gt;
        '''
        '''
        '''Get-WmiObject -Class Win32_OperatingSystem | Select-Object  @{label=&apos;LastBootUpTime&apos;;expression={$_.ConvertToDateTime($_.LastBootUpTime)}} | Format-Table -HideTableHeaders
        '''
        '''#Get-CimInstance -ClassName win32_operatingsystem | Select-Object LastBootUpTime | Format-Table -HideTable [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSQuery_LastBootUpTime() As String
            Get
                Return ResourceManager.GetString("PSQuery_LastBootUpTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;#
        '''.SYNOPSIS
        '''  Info on operating system version
        '''
        '''.DESCRIPTION
        '''  Get the info on the version of the operating system
        '''
        '''.NOTES
        '''  Version:        1.0
        '''  Author:         Ermanno Goletto
        '''  Creation Date:  2019-08-20
        '''#&gt;
        '''
        '''$ProductName=(Get-ItemProperty &quot;HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion&quot;).ProductName
        '''$Version=(Get-ItemProperty &quot;HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion&quot;).ReleaseId
        '''$CurrentBuild=(Get-ItemProperty &quot;HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion&quot;).CurrentBui [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSQuery_OSVersion() As String
            Get
                Return ResourceManager.GetString("PSQuery_OSVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a &lt;#
        '''.SYNOPSIS
        '''  Info on up time
        '''
        '''.DESCRIPTION
        '''  Get the time the operating system is up
        '''
        '''.NOTES
        '''  Version:        1.0
        '''  Author:         Ermanno Goletto
        '''  Creation Date:  2019-05-23
        '''#&gt;
        '''
        '''$LastBootUpTime=Get-WmiObject -Class Win32_OperatingSystem | Select-Object  @{label=&apos;LastBootUpTime&apos;;expression={$_.ConvertToDateTime($_.LastBootUpTime)}}
        '''$UpTime=New-TimeSpan -Start $LastBootUpTime.LastBootUpTime -End (Get-Date)
        '''$UpTime | Select-Object @{Label=&apos;Uptime&apos;; Expression={$_.Days.ToString() + &apos; day(s) [stringa troncata]&quot;;.
        '''</summary>
        Friend ReadOnly Property PSQuery_UpTime() As String
            Get
                Return ResourceManager.GetString("PSQuery_UpTime", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
